export const DUBLIN_CENTER = {
  lat: 53.3498,
  lng: -6.2603,
}

export const mockRestaurants = [
  {
    id: "1",
    name: "Dublin Pizza",
    address: "15 Dame Street, Dublin 2",
    phone: "+353 1 234 5678",
    bio: "Authentic wood-fired pizzas in the heart of Dublin. Family recipes passed down through generations.",
    menu_url: "https://example.com/menu",
    latitude: 53.3445,
    longitude: -6.2672,
    rating: 4.5,
    review_count: 127,
    cuisine: "Italian",
    price_range: "€€",
    image: "/italian-pizza-restaurant.jpg",
    photos: [
      "/dublin-pizza-margherita.jpg",
      "/dublin-pizza-interior.jpg",
      "/dublin-pizza-pepperoni.jpg",
      "/dublin-pizza-oven.jpg",
      "/dublin-pizza-quattro.jpg",
      "/dublin-pizza-dining.jpg",
    ],
  },
  {
    id: "2",
    name: "Irish Coffee Cafe",
    address: "42 Grafton Street, Dublin 2",
    phone: "+353 1 345 6789",
    bio: "Traditional Irish coffee and breakfast served all day. Cozy atmosphere with live music on weekends.",
    menu_url: "https://example.com/menu",
    latitude: 53.3425,
    longitude: -6.2597,
    rating: 4.7,
    review_count: 203,
    cuisine: "Irish Cafe",
    price_range: "€",
    image: "/irish-coffee-cafe.jpg",
  },
  {
    id: "3",
    name: "Diwali",
    address: "28 South William Street, Dublin 2",
    phone: "+353 1 456 7890",
    bio: "Contemporary Indian cuisine with a modern twist. Award-winning chef specializing in regional dishes.",
    menu_url: "https://example.com/menu",
    latitude: 53.3432,
    longitude: -6.2635,
    rating: 4.8,
    review_count: 189,
    cuisine: "Indian",
    price_range: "€€€",
    image: "/modern-indian-restaurant.png",
  },
  {
    id: "4",
    name: "The Temple Bar Grill",
    address: "47 Temple Bar, Dublin 2",
    phone: "+353 1 567 8901",
    bio: "Classic Irish pub fare and premium steaks. Live traditional music every night.",
    menu_url: "https://example.com/menu",
    latitude: 53.3456,
    longitude: -6.2644,
    rating: 4.3,
    review_count: 312,
    cuisine: "Irish Pub",
    price_range: "€€",
    image: "/irish-pub-restaurant.jpg",
  },
  {
    id: "5",
    name: "Sushi Samurai",
    address: "12 Wicklow Street, Dublin 2",
    phone: "+353 1 678 9012",
    bio: "Fresh sushi and Japanese cuisine. Daily specials featuring seasonal ingredients.",
    menu_url: "https://example.com/menu",
    latitude: 53.3418,
    longitude: -6.2615,
    rating: 4.6,
    review_count: 156,
    cuisine: "Japanese",
    price_range: "€€€",
    image: "/japanese-sushi-restaurant.png",
  },
  {
    id: "6",
    name: "La Boulangerie",
    address: "8 Aungier Street, Dublin 2",
    phone: "+353 1 789 0123",
    bio: "French bakery and bistro. Fresh pastries, croissants, and authentic French cuisine.",
    menu_url: "https://example.com/menu",
    latitude: 53.3398,
    longitude: -6.2645,
    rating: 4.4,
    review_count: 98,
    cuisine: "French",
    price_range: "€€",
    image: "/french-bakery-bistro.jpg",
  },
  {
    id: "7",
    name: "Spice Route",
    address: "34 Camden Street, Dublin 2",
    phone: "+353 1 890 1234",
    bio: "Pan-Asian fusion restaurant. Specializing in Thai, Vietnamese, and Malaysian dishes.",
    menu_url: "https://example.com/menu",
    latitude: 53.3365,
    longitude: -6.2658,
    rating: 4.5,
    review_count: 142,
    cuisine: "Asian Fusion",
    price_range: "€€",
    image: "/asian-fusion-restaurant.jpg",
  },
  {
    id: "8",
    name: "The Green Leaf",
    address: "19 George's Street, Dublin 2",
    phone: "+353 1 901 2345",
    bio: "Plant-based restaurant with creative vegan and vegetarian options. Sustainable and organic.",
    menu_url: "https://example.com/menu",
    latitude: 53.3412,
    longitude: -6.2688,
    rating: 4.7,
    review_count: 167,
    cuisine: "Vegan",
    price_range: "€€",
    image: "/vibrant-vegan-restaurant.png",
  },
  {
    id: "9",
    name: "Burger Republic",
    address: "56 O'Connell Street, Dublin 1",
    phone: "+353 1 012 3456",
    bio: "Gourmet burgers made with locally sourced Irish beef. Craft beers and loaded fries.",
    menu_url: "https://example.com/menu",
    latitude: 53.3498,
    longitude: -6.2603,
    rating: 4.2,
    review_count: 234,
    cuisine: "American",
    price_range: "€€",
    image: "/gourmet-burger-restaurant.png",
  },
  {
    id: "10",
    name: "Mediterranean Breeze",
    address: "23 Capel Street, Dublin 1",
    phone: "+353 1 123 4567",
    bio: "Greek and Mediterranean cuisine. Fresh seafood, mezze platters, and traditional dishes.",
    menu_url: "https://example.com/menu",
    latitude: 53.3478,
    longitude: -6.2689,
    rating: 4.6,
    review_count: 178,
    cuisine: "Mediterranean",
    price_range: "€€€",
    image: "/mediterranean-greek-restaurant.jpg",
  },
]

export const mockCoupons = [
  {
    id: "1",
    restaurant_id: "1",
    restaurant_name: "Dublin Pizza",
    name: "Summer Special",
    type: "percentage",
    discount_value: 20,
    description: "20% off your entire order",
    price_usdc: 5.99,
    quantity_available: 50,
    quantity_total: 100,
    expiry_date: "2025-12-31",
    terms: "Valid for dine-in and takeaway. Cannot be combined with other offers.",
  },
  {
    id: "2",
    restaurant_id: "2",
    restaurant_name: "Irish Coffee Cafe",
    name: "Breakfast Deal",
    type: "fixed_amount",
    discount_value: 5,
    description: "€5 off breakfast menu",
    price_usdc: 3.99,
    quantity_available: 100,
    quantity_total: 150,
    expiry_date: "2025-11-30",
    terms: "Valid Monday-Friday before 11am.",
  },
  {
    id: "3",
    restaurant_id: "3",
    restaurant_name: "Diwali",
    name: "Curry BOGO",
    type: "buy_one_get_one",
    discount_value: 0,
    description: "Buy one curry, get one free",
    price_usdc: 8.99,
    quantity_available: 30,
    quantity_total: 50,
    expiry_date: "2025-12-15",
    terms: "Equal or lesser value. Dine-in only.",
  },
  {
    id: "4",
    restaurant_id: "5",
    restaurant_name: "Sushi Samurai",
    name: "Sushi Platter Discount",
    type: "percentage",
    discount_value: 15,
    description: "15% off sushi platters",
    price_usdc: 6.99,
    quantity_available: 40,
    quantity_total: 60,
    expiry_date: "2025-12-31",
    terms: "Valid for orders over €30.",
  },
  {
    id: "5",
    restaurant_id: "8",
    restaurant_name: "The Green Leaf",
    name: "Dinner for Two",
    type: "fixed_amount",
    discount_value: 10,
    description: "€10 off dinner for two",
    price_usdc: 7.99,
    quantity_available: 25,
    quantity_total: 40,
    expiry_date: "2025-11-30",
    terms: "Minimum spend €40. Valid after 5pm.",
  },
  {
    id: "6",
    restaurant_id: "1",
    restaurant_name: "Dublin Pizza",
    name: "New Year Special",
    type: "percentage",
    discount_value: 25,
    description: "25% off all pizzas",
    price_usdc: 7.99,
    quantity_available: 0,
    quantity_total: 80,
    expiry_date: "2025-01-15",
    terms: "Expired coupon from New Year promotion.",
  },
]

export const mockUserCoupons = [
  {
    id: "1",
    coupon_id: "1",
    restaurant_name: "Dublin Pizza",
    description: "20% off your entire order",
    type: "percentage",
    value: 20,
    status: "active",
    purchased_at: "2025-01-15T10:30:00Z",
    expiration_date: "2025-12-31",
    nft_mint_address: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  },
  {
    id: "2",
    coupon_id: "2",
    restaurant_name: "Irish Coffee Cafe",
    description: "€5 off breakfast menu",
    type: "fixed",
    value: 5,
    status: "active",
    purchased_at: "2025-01-20T14:15:00Z",
    expiration_date: "2025-11-30",
    nft_mint_address: "8yLYug3DX98e08UKTEqcE6kCjfhfUqB94U[ARvKptdhBtV",
  },
  {
    id: "3",
    coupon_id: "4",
    restaurant_name: "Sushi Samurai",
    description: "15% off sushi platters",
    type: "percentage",
    value: 15,
    status: "redeemed",
    purchased_at: "2025-01-10T09:00:00Z",
    redeemed_at: "2025-01-25T19:30:00Z",
    expiration_date: "2025-12-31",
    nft_mint_address: "9zMZvh4EY09f19VLUFrdF7lDkgfigVrC05VBSwLqueiCW",
  },
]

export const mockBills = [
  {
    id: "1",
    restaurant_id: "1",
    restaurant_name: "Dublin Pizza",
    amount: 45.5,
    status: "approved",
    rating: 5,
    review: "Amazing pizza! The wood-fired crust was perfect and the toppings were fresh.",
    rewards_earned: 45,
    created_at: "2025-01-20T18:30:00Z",
    image_url: "/restaurant-receipt.png",
  },
  {
    id: "2",
    restaurant_id: "2",
    restaurant_name: "Irish Coffee Cafe",
    amount: 18.75,
    status: "approved",
    rating: 4,
    review: "Great coffee and friendly service. Will definitely come back!",
    rewards_earned: 19,
    created_at: "2025-01-22T10:15:00Z",
    image_url: "/cafe-receipt.jpg",
  },
  {
    id: "3",
    restaurant_id: "3",
    restaurant_name: "Diwali",
    amount: 67.2,
    status: "pending",
    rewards_earned: 67,
    created_at: "2025-01-28T20:00:00Z",
    image_url: "/restaurant-bill.jpg",
  },
  {
    id: "4",
    restaurant_id: "5",
    restaurant_name: "Sushi Samurai",
    amount: 52.3,
    status: "approved",
    rating: 5,
    review: "Best sushi in Dublin! Fresh fish and beautiful presentation.",
    rewards_earned: 52,
    created_at: "2025-01-25T19:45:00Z",
    image_url: "/sushi-receipt.png",
  },
  {
    id: "5",
    restaurant_id: "9",
    restaurant_name: "Burger Republic",
    amount: 28.9,
    status: "rejected",
    created_at: "2025-01-18T13:20:00Z",
    image_url: "/burger-receipt.png",
  },
]

export const mockReviews = [
  {
    id: "1",
    restaurant_id: "1",
    user_wallet: "7xKX...gAsU",
    rating: 5,
    review: "Amazing pizza! The wood-fired crust was perfect and the toppings were fresh.",
    created_at: "2025-01-20T18:45:00Z",
  },
  {
    id: "2",
    restaurant_id: "1",
    user_wallet: "8yLY...dhBtV",
    rating: 4,
    review: "Great atmosphere and delicious food. Slightly pricey but worth it.",
    created_at: "2025-01-18T20:15:00Z",
  },
  {
    id: "3",
    restaurant_id: "2",
    user_wallet: "9zMZ...eiCW",
    rating: 5,
    review: "Best Irish coffee in Dublin! Cozy spot for breakfast.",
    created_at: "2025-01-22T10:30:00Z",
  },
  {
    id: "4",
    restaurant_id: "3",
    user_wallet: "7xKX...gAsU",
    rating: 5,
    review: "Incredible Indian food. The butter chicken is a must-try!",
    created_at: "2025-01-15T21:00:00Z",
  },
  {
    id: "5",
    restaurant_id: "3",
    user_wallet: "8yLY...dhBtV",
    rating: 4,
    review: "Authentic flavors and generous portions. Service was excellent.",
    created_at: "2025-01-12T19:30:00Z",
  },
]

export const mockUserStats = {
  total_bills: 5,
  total_spent: 212.65,
  rewards_earned: 183,
  coupons_owned: 3,
  coupons_redeemed: 1,
  reviews_written: 4,
}

export const mockLoyaltyProgress = {
  current_tier: "Silver",
  points: 183,
  next_tier: "Gold",
  points_to_next_tier: 317,
  lifetime_points: 183,
  tier_benefits: ["Early access to new coupons", "5% bonus on all rewards", "Priority customer support"],
}

export const mockActivities = [
  {
    id: "1",
    type: "bill",
    description: "Uploaded bill at Diwali",
    amount: 67.2,
    date: "2025-01-28T20:00:00Z",
    status: "pending",
  },
  {
    id: "2",
    type: "review",
    description: "Reviewed Sushi Samurai",
    rating: 5,
    date: "2025-01-25T19:50:00Z",
  },
  {
    id: "3",
    type: "coupon",
    description: "Redeemed coupon at Sushi Samurai",
    date: "2025-01-25T19:30:00Z",
  },
  {
    id: "4",
    type: "bill",
    description: "Uploaded bill at Irish Coffee Cafe",
    amount: 18.75,
    date: "2025-01-22T10:15:00Z",
    status: "approved",
  },
  {
    id: "5",
    type: "coupon",
    description: "Purchased coupon for Irish Coffee Cafe",
    date: "2025-01-20T14:15:00Z",
  },
]

export const mockFeedPosts = [
  {
    id: "1",
    userName: "Sarah O'Brien",
    userAvatar: "/diverse-woman-avatar.png",
    restaurantName: "Dublin Pizza",
    caption: "Just had the most amazing Margherita pizza here! The wood-fired crust is absolutely perfect. 🍕",
    image: "/italian-pizza-restaurant.jpg",
    likes: 24,
    comments: 5,
    shares: 2,
    timestamp: "2 hours ago",
    liked: false,
    rating: 5,
  },
  {
    id: "2",
    userName: "James Murphy",
    userAvatar: "/man-avatar.png",
    restaurantName: "Irish Coffee Cafe",
    caption: "Perfect spot for morning coffee! The Irish coffee is legendary and the atmosphere is so cozy. ☕",
    image: "/irish-coffee-cafe.jpg",
    likes: 18,
    comments: 3,
    shares: 1,
    timestamp: "5 hours ago",
    liked: true,
    rating: 4,
  },
  {
    id: "3",
    userName: "Priya Sharma",
    userAvatar: "/woman-avatar-2.png",
    restaurantName: "Diwali",
    caption: "Best Indian food in Dublin! The butter chicken and naan were incredible. Can't wait to come back! 🍛",
    image: "/modern-indian-restaurant.png",
    likes: 42,
    comments: 8,
    shares: 5,
    timestamp: "1 day ago",
    liked: false,
    rating: 5,
  },
  {
    id: "4",
    userName: "Liam Walsh",
    userAvatar: "/man-avatar-2.png",
    restaurantName: "Sushi Samurai",
    caption: "Fresh sushi and beautiful presentation. The chef's special roll is a must-try! 🍣",
    image: "/japanese-sushi-restaurant.png",
    likes: 31,
    comments: 6,
    shares: 3,
    timestamp: "1 day ago",
    liked: true,
    rating: 5,
  },
  {
    id: "5",
    userName: "Emma Collins",
    userAvatar: "/woman-avatar-3.png",
    restaurantName: "The Green Leaf",
    caption: "Amazing vegan options! Even my meat-loving friends were impressed. The plant-based burger is unreal! 🌱",
    image: "/vibrant-vegan-restaurant.png",
    likes: 27,
    comments: 4,
    shares: 2,
    timestamp: "2 days ago",
    liked: false,
    rating: 4,
  },
  {
    id: "6",
    userName: "Connor Ryan",
    userAvatar: "/man-avatar-3.png",
    restaurantName: "Burger Republic",
    caption: "These gourmet burgers are next level! Perfectly cooked and the loaded fries are addictive. 🍔",
    image: "/gourmet-burger-restaurant.png",
    likes: 35,
    comments: 7,
    shares: 4,
    timestamp: "2 days ago",
    liked: false,
    rating: 5,
  },
  {
    id: "7",
    userName: "Sophie Martin",
    userAvatar: "/woman-avatar-4.png",
    restaurantName: "La Boulangerie",
    caption: "Authentic French pastries that transport you to Paris! The croissants are buttery perfection. 🥐",
    image: "/french-bakery-bistro.jpg",
    likes: 29,
    comments: 5,
    shares: 2,
    timestamp: "3 days ago",
    liked: true,
    rating: 5,
  },
  {
    id: "8",
    userName: "Michael Chen",
    userAvatar: "/man-avatar.png",
    restaurantName: "Dublin Pizza",
    caption: "Third time this month! Can't get enough of their Diavola pizza. The spicy kick is perfect! 🌶️🍕",
    image: "/italian-pizza-restaurant.jpg",
    likes: 19,
    comments: 4,
    shares: 1,
    timestamp: "4 days ago",
    liked: false,
    rating: 5,
  },
]

export const mockOwnerAnalytics = {
  stats: {
    totalRevenue: 45280,
    revenueGrowth: 12.5,
    totalOrders: 1247,
    ordersGrowth: 8.3,
    activeCustomers: 892,
    customerGrowth: 15.2,
    averageRating: 4.5,
    totalReviews: 127,
  },
  revenueData: [
    { day: "Mon", revenue: 5200 },
    { day: "Tue", revenue: 4800 },
    { day: "Wed", revenue: 6100 },
    { day: "Thu", revenue: 5900 },
    { day: "Fri", revenue: 8200 },
    { day: "Sat", revenue: 9500 },
    { day: "Sun", revenue: 7800 },
  ],
  popularItems: [
    { name: "Margherita", orders: 156 },
    { name: "Pepperoni", orders: 142 },
    { name: "Quattro Formaggi", orders: 98 },
    { name: "Diavola", orders: 87 },
    { name: "Vegetariana", orders: 76 },
  ],
  recentReviews: [
    {
      id: "1",
      userName: "Sarah O'Brien",
      userAvatar: "/diverse-woman-avatar.png",
      rating: 5,
      comment: "Amazing pizza! The wood-fired crust was perfect and the toppings were fresh.",
      date: "2 days ago",
    },
    {
      id: "2",
      userName: "James Murphy",
      userAvatar: "/man-avatar.png",
      rating: 4,
      comment: "Great atmosphere and delicious food. Slightly pricey but worth it.",
      date: "3 days ago",
    },
    {
      id: "3",
      userName: "Emma Collins",
      userAvatar: "/woman-avatar-3.png",
      rating: 5,
      comment: "Best pizza in Dublin! Will definitely be back.",
      date: "5 days ago",
    },
  ],
}

export const mockMenuItems = [
  {
    id: "1",
    name: "Margherita Pizza",
    category: "pizza",
    description: "Classic tomato sauce, fresh mozzarella, basil, and olive oil",
    price: 12.99,
    available: true,
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    category: "pizza",
    description: "Tomato sauce, mozzarella, and premium pepperoni",
    price: 14.99,
    available: true,
  },
  {
    id: "3",
    name: "Quattro Formaggi",
    category: "pizza",
    description: "Four cheese blend: mozzarella, gorgonzola, parmesan, and ricotta",
    price: 15.99,
    available: true,
  },
  {
    id: "4",
    name: "Diavola Pizza",
    category: "pizza",
    description: "Spicy salami, chili flakes, tomato sauce, and mozzarella",
    price: 15.49,
    available: true,
  },
  {
    id: "5",
    name: "Vegetariana Pizza",
    category: "pizza",
    description: "Grilled vegetables, tomato sauce, mozzarella, and fresh herbs",
    price: 13.99,
    available: true,
  },
  {
    id: "6",
    name: "Bruschetta",
    category: "appetizer",
    description: "Toasted bread with fresh tomatoes, garlic, basil, and olive oil",
    price: 7.99,
    available: true,
  },
  {
    id: "7",
    name: "Garlic Bread",
    category: "appetizer",
    description: "Wood-fired bread with garlic butter and herbs",
    price: 5.99,
    available: true,
  },
  {
    id: "8",
    name: "Caprese Salad",
    category: "appetizer",
    description: "Fresh mozzarella, tomatoes, basil, and balsamic glaze",
    price: 8.99,
    available: true,
  },
  {
    id: "9",
    name: "Tiramisu",
    category: "dessert",
    description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
    price: 6.99,
    available: true,
  },
  {
    id: "10",
    name: "Panna Cotta",
    category: "dessert",
    description: "Creamy vanilla dessert with berry compote",
    price: 6.49,
    available: false,
  },
  {
    id: "11",
    name: "Italian Soda",
    category: "beverage",
    description: "Sparkling water with fruit syrup",
    price: 3.99,
    available: true,
  },
  {
    id: "12",
    name: "Espresso",
    category: "beverage",
    description: "Strong Italian coffee",
    price: 2.99,
    available: true,
  },
]
